services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
    depends_on:
      - db
      - cache
  db:
    image: postgres:15.3
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./.pgdata:/var/lib/postgresql/data # Volume for persisting PostgreSQL data
    ports:
      - 54323:5432
  cache:
    image: redis:alpine
    ports:
      - 6379:6379
